"""First migration

Revision ID: 10aaad89b09e
Revises: aeff2ae945a8
Create Date: 2021-10-05 13:48:39.894860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aaad89b09e'
down_revision = 'aeff2ae945a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
